### ISSUE TITLE
Formatting is incorrect for strings containing an apostrophe

### ISSUE THREAD

**Issue by jdeeny** [olvyko/language-ron#1]
The text after the apostrophe is miscolored until a another apostrophe is encountered, like it is a 'closing apostrophe'.
![screenshot1](https://user-images.githubusercontent.com/409859/64929256-30ed9200-d7e1-11e9-8fa7-0091acb6afa9.png)
![screenshot2](https://user-images.githubusercontent.com/409859/64929259-3e0a8100-d7e1-11e9-9eb3-11a6bdeb63e2.png)
![screenshot3](https://user-images.githubusercontent.com/409859/64929267-62fef400-d7e1-11e9-9543-4cf80ae08fe5.png)

**Comment by olvyko** [comment]
This bug was fixed in the new version.
